export const EDIT_TEMPLATE_ACTION_CONSTANTS = {
  EDIT_TEMPLATE_REQUEST: "EDIT_TEMPLATE_REQUEST",
  EDIT_TEMPLATE_SUCCESS: "EDIT_TEMPLATE_SUCCESS",
  EDIT_TEMPLATE_FAILURE: "EDIT_TEMPLATE_FAILURE",
};
