export const USER_ACTION_TYPES = {
  // * GET USERS
  //////////////

  // * SINGLE
  ///////////
  GET_ONE_USER_REQUEST: "GET_ONE_USER_REQUEST",
  GET_ONE_USER_SUCCESS: "GET_ONE_USER_SUCCESS",
  GET_ONE_USER_FAILURE: "GET_ONE_USER_FAILURE",

  // * ALL
  ////////
  GET_USERS_REQUEST: "GET_USERS_REQUEST",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILURE: "GET_USERS_FAILURE",

  // * CREATE
  ///////////
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  // * UPDATE
  ////////////
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

  // *DELETE
  //////////
  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
};
