export const CREATE_TEMPLATE_ACTION_CONSTANTS = {
  CREATE_TEMPLATE_REQUEST: "CREATE_TEMPLATE_REQUEST",
  CREATE_TEMPLATE_SUCCESS: "CREATE_TEMPLATE_SUCCESS",
  CREATE_TEMPLATE_FAILURE: "CREATE_TEMPLATE_FAILURE",
};
