name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
  MarketingToolSonarScan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: MarketingToolSonarAnalyzation
        uses: sonarsource/sonarcloud-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organisation=tanmay-hornbook
            -Dsonar.projectKey=Marketing-tool
